name: My Workflows
on:
  push:
    paths:
      - '!README.md'
      - '!build/**'
      - '**.kt'
    branches:
      - 'master'
      - 'release/**'
      - '!develop/**'
jobs:
  say-hi:
    runs-on: macos-latest
    steps:
      - run: echo Xin chao!
